export const LOGIN_INITIATE = "LOGIN_INITIATE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_INITIATE = "LOGOUT_INITIATE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const SET_USER = "SET_USER";

export const FETCH_PRODUCTS_INITIATE = "FETCH_PRODUCTS_INITIATE";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

export const ADD_PRODUCT_INITIATE = "ADD_PRODUCT_INITIATE";
export const EDIT_PRODUCT_INITIATE = "EDIT_PRODUCT_INITIATE";
export const DELETE_PRODUCT_INITIATE = "DELETE_PRODUCT_INITIATE";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_INITIATE_SUCCESS";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_INITIATE_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_INITIATE_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
